% -------------------------------------------------------------------------
% Evaluate segmentation
% -------------------------------------------------------------------------
% Cristina Almagro-Perez, ETH Zürich, 2023
% -------------------------------------------------------------------------
clear;clc;close all;
current_directory = pwd;
[parent_directory, ~, ~] = fileparts(current_directory);
path(path,[parent_directory,'/base/natsortfiles/']);
% -------------------------------------------------------------------------
% Please select the following:
% 1. model (str) : FCN or cGAN (cGAN gave best results in terms of virtual staining)
% 2. option1: overlay segmentation masks from Ilastik, manual annotations, and
% the proposed approach (CT virtual staining + deconvolution) - Fig. 4.17 of Master Thesis
% 3. option2: calculate segmentation matrics (DSC,Precision,Recall,Accuracy) - Table 4.5
model='cGAN'; 
option1=1;
option2=0;
% -------------------------------------------------------------------------
% Overlay segmentation masks from Ilastik, manual annotations and
% the proposed approach (CT virtual staining + deconvolution)
% -------------------------------------------------------------------------
if option1

    % Directory to the µCT images
    pth_ct='';

    % Directory to the manually segmentated masks
    pth_manual='';

    % Directory to the masks generated by my model
    if strcmp(model,'FCN')
        % FCN (Fully Convolutional Network)
        pth_mymodel='';
    elseif strcmp(model,'cGAN')
        % cGAN (conditional Generative Adversarial Network)
        pth_mymodel='';
    end

    % Directory to the masks generated by Ilastik
    pth_Ilastik='';

    imlist=dir([pth_ct,'*.tif']);
    imlist=natsortfiles(imlist);

    kk=1; % select image index

    % Load images
    ct=imread([pth_ct,imlist(kk).name]);
    mask_manual=logical(imread([pth_manual,imlist(kk).name]));
    mask_mymodel=logical(imread([pth_mymodel,imlist(kk).name]));
    mask_Ilastik=logical(imread([pth_Ilastik,imlist(kk).name]));

    % Ensure all the images are at the same resolution
    mask_manual=imresize(mask_manual,size(mask_Ilastik));
    mask_mymodel=imresize(mask_mymodel,size(mask_Ilastik));
    ct=imresize(ct,size(mask_mymodel));

    % Create overlaid images
    colour=[255 152 229]/255;
    B_manual = labeloverlay(ct,mask_manual,'Colormap',colour,'Transparency',0.25);
    B_mymodel = labeloverlay(ct,mask_mymodel,'Colormap',colour,'Transparency',0.25);
    B_Ilastik = labeloverlay(ct,mask_Ilastik,'Colormap',colour,'Transparency',0.25);

    figure;
    subplot(1,3,1);imshow(B_manual);title("Manual");
    subplot(1,3,2);imshow(B_mymodel);title(model);
    subplot(1,3,3);imshow(B_Ilastik);title("Ilastik");
    set(gcf,'color','w');
end

% -------------------------------------------------------------------------
% Calculate segmentation metrics (precision, recall, accuracy, DSC)
% -------------------------------------------------------------------------
if option2

    fprintf("Calculating segmentation metrics... \n")
    % Directory to the masks generated by the proposed approach (virtual staining + colour deconvolution)
    if strcmp(model,'FCN')
        pth_mymodel='';
    elseif strcmp(model,'cGAN')
        pth_mymodel='';
    end

    % Directory to the manually annotated masks
    pth_manual='';

    % Directory to the masks generated by Ilastik
    pth_Ilastik='';

    imlist=dir([pth_manual,'*.tif']);
    imlist=natsortfiles(imlist);

    lim=2;
    % Proposed approach variables
    dsc_all=zeros(1,lim);
    precision_all=zeros(1,lim);
    recall_all=zeros(1,lim);
    accuracy_all=zeros(1,lim);
   

    % Ilastik variables
    dsc_all_I=zeros(1,lim);
    precision_all_I=zeros(1,lim);
    recall_all_I=zeros(1,lim);
    accuracy_all_I=zeros(1,lim);
    
    for kk=1:lim

        % Load segmentation masks
        mask_mymodel=logical(imread([pth_mymodel,imlist(kk).name]));
        mask_manual=logical(imread([pth_manual,imlist(kk).name]));
        mask_Ilastik=logical(imread([pth_Ilastik,imlist(kk).name]));
        
        % Resize so all masks are in the low-resolution volume (4 um/pixel)
        mask_manual=imresize(mask_manual,size(mask_Ilastik));
        mask_mymodel=imresize(mask_mymodel,size(mask_Ilastik));

        
        % Metrics for the proposed segmentation approach:
        dsc_all(1,kk)=dice(mask_manual,mask_mymodel);
        precision_all(1,kk) = precision_score(mask_manual,mask_mymodel);
        recall_all(1,kk) = recall_score(mask_manual,mask_mymodel);
        accuracy_all(1,kk) = accuracy_score(mask_manual,mask_mymodel);
       

        % Metrics for Ilastik:
        dsc_all_I(1,kk)=dice(mask_manual,mask_Ilastik);
        precision_all_I(1,kk) = precision_score(mask_manual,mask_Ilastik);
        recall_all_I(1,kk) = recall_score(mask_manual,mask_Ilastik);
        accuracy_all_I(1,kk) = accuracy_score(mask_manual,mask_Ilastik);   
    end
        % Proposed approach
        fprintf("###### Metrics of model %s ###### \n", model);
        fprintf("The average +/- std DSC with the manual mask is: %f +/- %f \n",mean(dsc_all),std(dsc_all));
        fprintf("The average +/- std PRECISION with the manual mask is: %f +/- %f \n",mean(precision_all),std(precision_all));
        fprintf("The average +/- std RECALL with the manual mask is: %f +/- %f \n",mean(recall_all),std(recall_all));
        fprintf("The average +/- std ACCURACY with the manual mask is: %f +/- %f \n",mean(accuracy_all),std(accuracy_all));
        
        % ILASTIK
        fprintf("###### Metrics of Ilastik  ###### \n");
        fprintf("The average +/- std DSC with the manual mask is: %f +/- %f \n",mean(dsc_all_I),std(dsc_all_I));
        fprintf("The average +/- std PRECISION with the manual mask is: %f +/- %f \n",mean(precision_all_I),std(precision_all_I));
        fprintf("The average +/- std RECALL with the manual mask is: %f +/- %f \n",mean(recall_all_I),std(recall_all_I));
        fprintf("The average +/- std ACCURACY with the manual mask is: %f +/- %f \n",mean(accuracy_all_I),std(accuracy_all_I));
        
end


% ---------------- Auxiliary functions -----------------------------------%
function precision = precision_score(groundtruth_mask, pred_mask)
    intersect = sum(pred_mask(:) .* groundtruth_mask(:));
    total_pixel_pred = sum(pred_mask(:));
    precision = mean(intersect ./ total_pixel_pred);
    precision = round(precision, 3);
end

function recall = recall_score(groundtruth_mask, pred_mask)
    intersect = sum(pred_mask(:) .* groundtruth_mask(:));
    total_pixel_truth = sum(groundtruth_mask(:));
    recall = mean(intersect ./ total_pixel_truth);
    recall = round(recall, 3);
end

function accuracy = accuracy_score(groundtruth_mask, pred_mask)
    intersect = sum(pred_mask(:) .* groundtruth_mask(:));
    denom=pred_mask + groundtruth_mask >0;
    total=sum(denom(:));
    accuracy= intersect /total;
end
% -------------------------------------------------------------------------
